Repository nabeelio/phpvms, pull requests merged in 2020-09, with the labels that each got.

#799 Detect the phpvms folder one root level above #798
  public/index.php
Labels: enhancement

#803 Update Laravel/composer dependencies
  composer.lock
Labels: dependencies

#804 Notifications fixes
  app/Contracts/Event.php
  app/Contracts/Notification.php
  app/Database/factories/UserFactory.php
  app/Events/AcarsUpdate.php
  app/Events/BaseEvent.php
  app/Events/CronHourly.php
  app/Events/CronMonthly.php
  app/Events/CronNightly.php
  app/Events/CronWeekly.php
  app/Events/Expenses.php
  app/Events/NewsAdded.php
  app/Events/PirepAccepted.php
  app/Events/PirepCancelled.php
  app/Events/PirepFiled.php
  app/Events/PirepPrefiled.php
  app/Events/PirepRejected.php
  app/Events/PirepUpdated.php
  app/Events/TestEvent.php
  app/Events/UserAccepted.php
  app/Events/UserRegistered.php
  app/Events/UserStateChanged.php
  app/Events/UserStatsChanged.php
  app/Notifications/EventHandler.php
  app/Notifications/Messages/AdminUserRegistered.php
  app/Notifications/Messages/NewsAdded.php
  app/Notifications/Messages/PirepAccepted.php
  app/Notifications/Messages/PirepRejected.php
  app/Notifications/Messages/PirepSubmitted.php
  app/Notifications/Messages/UserPending.php
  app/Notifications/Messages/UserRegistered.php
  app/Notifications/Messages/UserRejected.php
  app/Providers/EventServiceProvider.php
  tests/NewsTest.php
  tests/PIREPTest.php
Labels: bug

#805 Add MTOW and ZFW to aircraft editor #775
  app/Database/factories/AircraftFactory.php
  app/Database/migrations/2020_09_03_141152_aircraft_add_mtow.php
  app/Models/Aircraft.php
  resources/views/admin/aircraft/fields.blade.php
  tests/ApiTest.php
Labels: bug

#817 Disable autocomplete in admin forms #816
  composer.json
  resources/views/admin/aircraft/create.blade.php
  resources/views/admin/aircraft/edit.blade.php
  resources/views/admin/airlines/create.blade.php
  resources/views/admin/airlines/edit.blade.php
  resources/views/admin/airports/create.blade.php
  resources/views/admin/airports/edit.blade.php
  resources/views/admin/awards/create.blade.php
  resources/views/admin/awards/edit.blade.php
  resources/views/admin/expenses/create.blade.php
  resources/views/admin/expenses/edit.blade.php
  resources/views/admin/fares/create.blade.php
  resources/views/admin/fares/edit.blade.php
  resources/views/admin/flightfields/create.blade.php
  resources/views/admin/flightfields/edit.blade.php
  resources/views/admin/flights/create.blade.php
  resources/views/admin/flights/edit.blade.php
  resources/views/admin/pages/create.blade.php
  resources/views/admin/pages/edit.blade.php
  resources/views/admin/pirepfields/create.blade.php
  resources/views/admin/pirepfields/edit.blade.php
  resources/views/admin/pireps/create.blade.php
  resources/views/admin/pireps/edit.blade.php
  resources/views/admin/ranks/create.blade.php
  resources/views/admin/ranks/edit.blade.php
  resources/views/admin/roles/create.blade.php
  resources/views/admin/roles/edit.blade.php
  resources/views/admin/subfleets/create.blade.php
  resources/views/admin/subfleets/edit.blade.php
  resources/views/admin/userfields/create.blade.php
  resources/views/admin/userfields/edit.blade.php
  resources/views/admin/users/create.blade.php
  resources/views/admin/users/edit.blade.php
Labels: bug

#837 Updated index.js inside Map folder
  resources/js/maps/index.js
Labels: feature request

#839 Public JS files Updated!
  public/assets/admin/css/vendor.min.css.map
  public/assets/admin/js/app.js
  public/assets/admin/js/app.js.map
  public/assets/frontend/css/now-ui-kit.css.map
  public/assets/frontend/js/app.js
  public/assets/frontend/js/app.js.map
  public/assets/installer/js/app.js.map
  public/assets/vendor/ckeditor4/package.json
  public/mix-manifest.json
Labels: feature request

#843 Updated Module Files
  resources/stubs/modules/route-provider.stub
  resources/stubs/modules/routes.stub
Labels: bug

#845 Updated Module Route Service Provider
  config/modules_statuses.json
  resources/stubs/modules/route-provider.stub
Labels: bug

#846 Fix subfleets not returning proper fare counts #831
  app/Services/UserService.php
  tests/TestData.php
  tests/UserTest.php
Labels: bug

#849 Make sure proper subfleets are returned as part of the user profile #848
  app/Http/Controllers/Api/UserController.php
  app/Http/Resources/User.php
  app/Services/UserService.php
  tests/TestData.php
  tests/UserTest.php
Labels: bug
