Repository nabeelio/phpvms, pull requests merged in 2020-02, with the labels that each got.

#534 Fix PIREP edit endpoint
  app/Http/Routes/web.php
Labels: bug

#535 Fix import during flight cron #532
  app/Cron/Hourly/RemoveExpiredLiveFlights.php
Labels: bug

#536 PIREPS resource except for show
  app/Http/Routes/web.php
Labels: bug

#537 Use optional() around the airport fields
  app/Services/GeoService.php
  resources/views/admin/flights/show_fields.blade.php
  resources/views/admin/flights/table.blade.php
  resources/views/layouts/default/airports/show.blade.php
  resources/views/layouts/default/flights/show.blade.php
  resources/views/layouts/default/flights/table.blade.php
Labels: bug

#539 Add link to download ACARS config from profile
  app/Http/Controllers/Frontend/ProfileController.php
  app/Http/Routes/web.php
  resources/views/layouts/default/profile/index.blade.php
  resources/views/system/acars/config.blade.php
Labels: enhancement

#540 ACARS XML config file download
  resources/views/system/acars/config.blade.php
Labels: feature

#543 Distro zip file from tar file #449
  .travis/deploy_script.sh
  app/Providers/EventServiceProvider.php
  composer.json
  composer.lock
  config/installer.php
  config/self-update.php
  resources/views/vendor/self-update/mails/update-available.blade.php
  resources/views/vendor/self-update/self-update.blade.php
Labels: enhancement

#544 Auto-update functionality #449
  .travis.yml
  .travis/deploy_script.sh
  app/Http/Controllers/Admin/MaintenanceController.php
  app/Http/Routes/admin.php
  config/self-update.php
  resources/views/admin/maintenance/index.blade.php
  resources/views/admin/maintenance/update.blade.php
Labels: feature

#542 Spanish files translation
  resources/lang/es/auth.php
  resources/lang/es/flights.php
  resources/lang/es/passwords.php
  resources/lang/es/profile.php
  resources/lang/es/user.php
  resources/lang/es/validation.php
Labels: enhancement

#545 Auto update #449
  app/Http/Controllers/Admin/MaintenanceController.php
  app/Http/Routes/admin.php
  app/Providers/EventServiceProvider.php
  app/Services/VersionService.php
  app/Support/HttpClient.php
  config/app.php
  config/phpvms.php
  config/self-update.php
  modules/Updater/Http/Controllers/UpdateController.php
  modules/Updater/Lib/VmsRepositoryType.php
  modules/Updater/Providers/UpdateServiceProvider.php
  modules/Updater/Resources/views/downloader/downloader.blade.php
  resources/views/admin/maintenance/update.blade.php
  resources/views/layouts/default/nav.blade.php
Labels: feature

#546 Add checkbox to clear previous data when importing #490
  app/Http/Controllers/Admin/AircraftController.php
  app/Http/Controllers/Admin/AirportController.php
  app/Http/Controllers/Admin/ExpenseController.php
  app/Http/Controllers/Admin/FareController.php
  app/Http/Controllers/Admin/FlightController.php
  app/Http/Controllers/Admin/SubfleetController.php
  app/Http/Controllers/Admin/Traits/Importable.php
  app/Models/Enums/ImportExportType.php
  resources/views/admin/common/import.blade.php
Labels: enhancement

#547 Cleanup Utils #467
  .travis.yml
  .travis/deploy_script.sh
  app/Console/Commands/AcarsReplay.php
  app/Contracts/Award.php
  app/Facades/Utils.php
  app/Http/Controllers/Admin/PirepController.php
  app/Http/Controllers/Admin/UserController.php
  app/Http/Controllers/Auth/RegisterController.php
  app/Http/Controllers/Frontend/PirepController.php
  app/Http/Controllers/Frontend/ProfileController.php
  app/Providers/DirectiveServiceProvider.php
  app/Support/Dates.php
  app/Support/HttpClient.php
  app/Support/Units/Time.php
  app/Support/Utils.php
  config/app.php
  modules/Importer/Services/Importers/UserImport.php
  modules/Installer/Http/Controllers/InstallerController.php
  resources/views/admin/aircraft/table.blade.php
  resources/views/admin/pireps/pirep_card.blade.php
  resources/views/admin/pireps/show_fields.blade.php
  resources/views/admin/users/fields.blade.php
  resources/views/layouts/default/dashboard/index.blade.php
  resources/views/layouts/default/pireps/pirep_card.blade.php
  resources/views/layouts/default/profile/index.blade.php
  resources/views/layouts/default/users/table.blade.php
  tests/UtilsTest.php
Labels: enhancement

#548 Add additional events for PIREP states #436
  app/Events/PirepCancelled.php
  app/Events/PirepPrefiled.php
  app/Events/PirepUpdated.php
  app/Http/Controllers/Api/PirepController.php
  app/Services/PirepService.php
Labels: enhancement

#549 Set expenses on specific flight types #348
  app/Database/migrations/2020_02_12_141152_expenses_add_flight_type.php
  app/Http/Controllers/Admin/ExpenseController.php
  app/Models/Expense.php
  app/Models/Pirep.php
  app/Models/Traits/ReferenceTrait.php
  app/Services/Finance/PirepFinanceService.php
  resources/views/admin/expenses/fields.blade.php
  tests/FinanceTest.php
Labels: feature

#551 Add Google Analytics tracking ID to settings and to main template #382
  app/Database/seeds/settings.yml
  resources/views/admin/menu.blade.php
  resources/views/admin/settings/table.blade.php
  resources/views/layouts/default/app.blade.php
Labels: feature

#550 Add logo to the flights page if its set #417
  resources/views/layouts/default/flights/table.blade.php
Labels: enhancement

#555 Fix migrations when table prefix is involved #442
  app/Contracts/Controller.php
  app/Database/migrations/2019_06_19_220910_add_readonly_to_roles.php
  app/Database/migrations/2019_07_16_141152_users_add_pilot_id.php
  app/Database/migrations/2019_09_16_141152_pireps_change_state_type.php
  modules/Installer/Http/Controllers/InstallerController.php
  modules/Installer/Resources/views/flash/message.blade.php
  modules/Installer/Resources/views/install/steps/step1-requirements.blade.php
Labels: bug

#556 Add the argc_argv flag for the cgi exec #553
  app/Services/CronService.php
Labels: enhancement

#557 Refresh theme cache on settings page load #554
  app/Http/Controllers/Admin/SettingsController.php
  resources/views/admin/settings/table.blade.php
  resources/views/layouts/.gitignore
Labels: bug

#562 Missing $subfleet error on bids page #561
  app/Http/Controllers/Frontend/FlightController.php
  resources/views/layouts/default/flights/search.blade.php
Labels: bug

#563 Add extra check for being set #560
  app/Http/Controllers/Frontend/ProfileController.php
  resources/views/layouts/default/profile/index.blade.php
Labels: bug

#564 Add bcmath to the required extensions list #558
  modules/Installer/Config/config.php
Labels: enhancement

#565 Route not found error for Pirep::resource() call #559
  app/Http/Routes/web.php
  composer.lock
Labels: bug

#571 Fix the namespace path on updater templates #570
  modules/Updater/Resources/views/downloader/downloader.blade.php
  modules/Updater/Resources/views/index-start.blade.php
  modules/Updater/Resources/views/steps/step1-no-update.blade.php
  modules/Updater/Resources/views/steps/step1-update-available.blade.php
  modules/Updater/Resources/views/steps/step2-migrations-done.blade.php
  modules/Updater/Resources/views/steps/step3-update-complete.blade.php
Labels: bug

#573 Upsert on ACARS positions #572
  app/Http/Controllers/Api/AcarsController.php
  app/Http/Controllers/Api/PirepController.php
  app/Models/Traits/HashIdTrait.php
  app/Support/Utils.php
  config/themes.php
  tests/AcarsTest.php
Labels: bug

#577 Fix edit pilot error (Facade\Utils missing) #576
  resources/views/admin/users/fields.blade.php
Labels: bug

#578 Upstream null version; build version tags not being saved properly #575
  .travis/deploy_script.sh
  app/Console/Commands/Version.php
  app/Http/Composers/VersionComposer.php
  app/Providers/ComposerServiceProvider.php
  app/Services/VersionService.php
  config/app.php
  config/version.yml
  resources/views/admin/app.blade.php
  resources/views/admin/sidebar.blade.php
Labels: bug

#582 Change fuel used to optional #512
  app/Models/Pirep.php
Labels: bug

#581 Respect home hubs setting for registration #580
  Makefile
  app/Database/factories/UserFactory.php
  app/Http/Controllers/Auth/RegisterController.php
  app/Http/Requests/CreateUserRequest.php
  app/Services/UserService.php
  composer.json
  composer.lock
  modules/Installer/Http/Controllers/InstallerController.php
  resources/views/layouts/default/pireps/show.blade.php
  tests/RegistrationTest.php
  tests/UserTest.php
Labels: bug

#583 Fix rowmapper generator, check for fields, map users #443
  app/Services/UserService.php
  modules/Importer/Resources/views/step1-configure.blade.php
  modules/Importer/Services/BaseImporter.php
  modules/Importer/Services/ImporterService.php
  modules/Importer/Services/Importers/AircraftImporter.php
  modules/Importer/Services/Importers/AirlineImporter.php
  modules/Importer/Services/Importers/AirportImporter.php
  modules/Importer/Services/Importers/ClearDatabase.php
  modules/Importer/Services/Importers/FinalizeImporter.php
  modules/Importer/Services/Importers/FlightImporter.php
  modules/Importer/Services/Importers/GroupImporter.php
  modules/Importer/Services/Importers/PirepImporter.php
  modules/Importer/Services/Importers/RankImport.php
  modules/Importer/Services/Importers/UserImport.php
  modules/Importer/Utils/IdMapper.php
  modules/Importer/Utils/ImporterDB.php
  resources/views/system/acars/config.blade.php
Labels: enhancement

#584 User country mapping; ignore unused groups #443
  app/Services/RoleService.php
  app/Support/Countries.php
  modules/Importer/Services/Importers/GroupImporter.php
  modules/Importer/Services/Importers/UserImport.php
Labels: bug

#586 (Importer) Set the pay rate for the ranks #443
  modules/Importer/Services/Importers/RankImport.php
Labels: enhancement

#587 Recalcuate aircraft stats in nightly cron and importer #585 #443
  app/Cron/Nightly/RecalculateStats.php
  app/Services/AircraftService.php
  modules/Importer/Resources/views/step1-configure.blade.php
  modules/Importer/Services/Importers/FinalizeImporter.php
  tests/PIREPTest.php
Labels: enhancement

#588 Import expense and ledger entries #443
  app/Services/FinanceService.php
  app/Support/Money.php
  modules/Importer/Services/BaseImporter.php
  modules/Importer/Services/ImporterService.php
  modules/Importer/Services/Importers/ClearDatabase.php
  modules/Importer/Services/Importers/ExpenseImporter.php
  modules/Importer/Services/Importers/ExpenseLogImporter.php
  modules/Importer/Services/Importers/LedgerImporter.php
  modules/Importer/Services/Importers/RankImport.php
  modules/Importer/Services/Importers/SettingsImporter.php
  modules/Importer/Utils/ImporterDB.php
Labels: bug

#591 Remove 4 char restriction from ICAO; use decimal type for lat/lon #590
  app/Database/migrations/2020_02_26_044305_modify_airports_coordinates.php
  app/Models/Airport.php
Labels: enhancement

#592 Remove airport length restrictions #590
  app/Http/Requests/Acars/FileRequest.php
  app/Http/Requests/Acars/PrefileRequest.php
  app/Http/Requests/Acars/UpdateRequest.php
  app/Models/Flight.php
Labels: enhancement

#594 Module/plugin installation working #593
  app/Console/Commands/ClearCaches.php
  composer.json
  composer.lock
  config/modules.php
  modules/.gitignore
  modules/Sample/Awards/SampleAward.php
  modules/Sample/Config/config.php
  modules/Sample/Database/seeders/SampleDatabaseSeeder.php
  modules/Sample/Http/Controllers/Admin/AdminController.php
  modules/Sample/Http/Controllers/Api/SampleController.php
  modules/Sample/Http/Controllers/SampleController.php
  modules/Sample/Http/Routes/admin.php
  modules/Sample/Http/Routes/api.php
  modules/Sample/Http/Routes/web.php
  modules/Sample/Listeners/TestEventListener.php
  modules/Sample/Models/SampleTable.php
  modules/Sample/Providers/EventServiceProvider.php
  modules/Sample/Providers/SampleServiceProvider.php
  modules/Sample/Resources/views/admin/create.blade.php
  modules/Sample/Resources/views/admin/index.blade.php
  modules/Sample/Resources/views/index.blade.php
  modules/Sample/Resources/views/layouts/admin.blade.php
  modules/Sample/Resources/views/layouts/frontend.blade.php
  modules/Sample/composer.json
  modules/Sample/module.json
  resources/stubs/modules/composer.stub
  tests/AwardsTest.php
Labels: feature

#596 Installer fixes, remove bcmath, fix design
  composer.json
  modules/Installer/Config/config.php
  modules/Installer/Http/Controllers/InstallerController.php
  modules/Installer/Resources/views/app.blade.php
  modules/Installer/Resources/views/install/steps/step1-requirements.blade.php
  modules/Installer/Resources/views/install/steps/step2-db.blade.php
  resources/docker/php/Dockerfile
  resources/sass/now-ui/now-ui-kit/_sections.scss
Labels: enhancement

#597 Table prefixes not being added to indexes
  app/Contracts/Enum.php
  config/database.php
  modules/Importer/Http/Controllers/ImporterController.php
  modules/Importer/Resources/views/app.blade.php
  modules/Importer/Resources/views/step1-configure.blade.php
  modules/Importer/Services/ImporterService.php
  modules/Installer/Resources/views/app.blade.php
  modules/Installer/Resources/views/install/steps/step1-requirements.blade.php
  modules/Installer/Resources/views/install/steps/step2-db.blade.php
  modules/Updater/Resources/views/app.blade.php
  resources/stubs/installer/config.stub
Labels: bug

#600 METAR parsing infinite loop bugfix #599
  app/Services/Metar/AviationWeather.php
  app/Widgets/Weather.php
  tests/MetarTest.php
  tests/data/aviationweather/unknown.xml
Labels: bug
