Repository nabeelio/phpvms, pull requests merged in 2021-08, with the labels that each got.

#1271 Trap exception/check for module existing on disk #1211
  app/Http/Controllers/Admin/ModulesController.php
  app/Services/ModuleService.php
  resources/lang/zh/aircraft.php
Labels: bug

#1273 Add ability to launch acars for flight/bid #1272
  app/Http/Controllers/Frontend/FlightController.php
  app/Services/ModuleService.php
  resources/views/layouts/default/flights/table.blade.php
Labels: enhancement, acars

#1277 Cast the user ID to int in the sb model
  app/Models/SimBrief.php
Labels: bug

#1282 Update pirep_card.blade.php
  resources/views/admin/pireps/pirep_card.blade.php
Labels: enhancement

#1283 Remove SimBrief with Bid
  app/Services/BidService.php
Labels: enhancement
