Repository nabeelio/phpvms, pull requests merged in 2021-05, with the labels that each got.

#1167 Block refiling of PIREPs
  app/Exceptions/PirepError.php
  app/Http/Controllers/Api/PirepController.php
  app/Models/Pirep.php
  app/Services/Metar/AviationWeather.php
  app/Services/PirepService.php
  composer.lock
  tests/AcarsTest.php
Labels: bug

#1169 Disable autocomplete on admin email field
  resources/views/admin/users/fields.blade.php
Labels: bug

#1170 Allow session lifetime to be set in env variables
  config/session.php
Labels: enhancement

#1171 Delete users without PIREPS; pilot leave fix
  app/Models/User.php
  app/Services/UserService.php
  tests/TestData.php
  tests/UserTest.php
Labels: bug

#1172 100LL and MOGAS Fuel Cost
  app/Database/seeds/settings.yml
  app/Models/Subfleet.php
  app/Services/Finance/PirepFinanceService.php
Labels: enhancement

#1173 Fix for duplicated/wrong expenses being applied #915
  app/Models/Expense.php
  app/Services/Finance/PirepFinanceService.php
  tests/FinanceTest.php
Labels: bug

#1176 Fix AirportController (Frontend)
  app/Http/Controllers/Frontend/AirportController.php
Labels: bug

#1178 PirepCancelled Event (Cron Expired Pirep Deletion)
  app/Cron/Hourly/RemoveExpiredLiveFlights.php
Labels: bug

#1118 Update to PHP 8
  .github/workflows/build.yml
  composer.json
  composer.lock
  config/app.php
Labels: enhancement

#1185 Fix Installer: Completed Blade
  resources/views/system/installer/install/steps/step3a-completed.blade.php
Labels: enhancement

#1193 Days::in should use in_mask; tests coverage #1180
  app/Models/Enums/Days.php
  tests/FlightTest.php
Labels: bug

#1192 Update Flight Controller to fix an issue
  app/Http/Controllers/Admin/FlightController.php
Labels: bug

#1194 intl dependency/polyfill updates
  composer.json
  composer.lock
Labels: bug

#1195 Remove the autoupdater #1133
  app/Cron/Nightly/NewVersionCheck.php
  app/Http/Controllers/Admin/MaintenanceController.php
  app/Http/Controllers/System/UpdateController.php
  app/Providers/RouteServiceProvider.php
  composer.lock
  resources/views/admin/maintenance/update.blade.php
  resources/views/admin/menu.blade.php
  resources/views/admin/modules/index.blade.php
  resources/views/system/updater/downloader/downloader.blade.php
Labels: core

#1174 Use queues for notifications #1154
  app/Console/Commands/EmailTest.php
  app/Console/Commands/ProcessQueue.php
  app/Console/Cron/JobQueue.php
  app/Console/Kernel.php
  app/Contracts/Command.php
  app/Listeners/MessageLoggedListener.php
  app/Models/News.php
  app/Notifications/Messages/AdminUserRegistered.php
  app/Notifications/Messages/NewsAdded.php
  app/Notifications/Messages/PirepAccepted.php
  app/Notifications/Messages/PirepRejected.php
  app/Notifications/Messages/PirepSubmitted.php
  app/Notifications/Messages/UserPending.php
  app/Notifications/Messages/UserRegistered.php
  app/Notifications/Messages/UserRejected.php
  app/Providers/EventServiceProvider.php
  composer.json
  composer.lock
  config/logging.php
  resources/stubs/installer/env.stub
Labels: enhancement

#1197 Make fuel_used an optional field in PIREP file
  app/Http/Requests/Acars/FileRequest.php
  app/Listeners/MessageLoggedListener.php
  phpunit.xml
Labels: enhancement

#1198 5 char ICAO support #1052
  app/Database/factories/AirportFactory.php
  app/Database/migrations/2021_05_21_141152_increase_icao_sizes.php
  tests/AirportTest.php
  tests/ApiTest.php
Labels: enhancement

#1200 Remove Scripts
  resources/views/admin/flights/create.blade.php
  resources/views/admin/flights/fields.blade.php
Labels: bug

#1203 Add --force flag to migrations
  app/Services/Installer/MigrationService.php
  app/Services/ModuleService.php
  tests/TestCase.php
Labels: bug

#1204 Fix Admin: UserController and Flight Edit
  app/Http/Controllers/Admin/UserController.php
  resources/views/admin/flights/fields.blade.php
Labels: bug

#1205 Add ability to search Flights by Code
  resources/lang/en/flights.php
  resources/lang/es/flights.php
  resources/lang/it/flights.php
  resources/lang/pt-br/flights.php
  resources/views/layouts/default/flights/search.blade.php
Labels: enhancement

#1207 Show only used Flight Types at Flight Search
  app/Http/Controllers/Frontend/FlightController.php
Labels: enhancement

#1212 Add GD PHP Extension for docker container
  Dockerfile
Labels: enhancement
