Repository nabeelio/phpvms, pull requests merged in 2021-03, with the labels that each got.

#1053 Fix Advanced Fuel Calculations
  app/Services/Finance/PirepFinanceService.php
Labels: bug

#1054 Refactoring Simbrief fares and aircraft
  app/Database/migrations/2021_03_01_044305_add_aircraft_to_simbrief.php
  app/Database/seeds/dev/sample.yml
  app/Http/Controllers/Frontend/PirepController.php
  app/Http/Controllers/Frontend/SimBriefController.php
  app/Http/Resources/Fare.php
  app/Http/Resources/SimBrief.php
  app/Http/Resources/User.php
  app/Models/Fare.php
  app/Models/Pirep.php
  app/Models/SimBrief.php
  app/Services/BidService.php
  app/Services/FareService.php
  app/Services/SimBriefService.php
  public/assets/global/js/simbrief.apiv1.js
  resources/views/layouts/default/flights/simbrief_form.blade.php
  resources/views/layouts/default/flights/table.blade.php
  resources/views/layouts/default/pireps/fares.blade.php
  tests/SimBriefTest.php
Labels: enhancement

#1055 Implement PIREP deletion #1014
  app/Console/Kernel.php
  app/Cron/Hourly/DeletePireps.php
  app/Cron/Monthly/ApplyExpenses.php
  app/Cron/Nightly/ApplyExpenses.php
  app/Cron/Nightly/ClearExpiredSimbrief.php
  app/Cron/Nightly/NewVersionCheck.php
  app/Cron/Nightly/PilotLeave.php
  app/Cron/Nightly/RecalculateBalances.php
  app/Cron/Nightly/RecalculateStats.php
  app/Cron/Nightly/SetActiveFlights.php
  app/Database/seeds/settings.yml
  app/Http/Controllers/Admin/PirepController.php
  app/Http/Controllers/Frontend/PirepController.php
  app/Providers/CronServiceProvider.php
  app/Services/PirepService.php
  resources/views/admin/pireps/actions.blade.php
Labels: enhancement

#1056 Check for valid reference object in RecurringFinance
  app/Services/Finance/RecurringFinanceService.php
Labels: bug

#1058 Update Laravel and other dependencies
  .github/scripts/env.php
  .github/workflows/build.yml
  README.md
  app/Providers/AppServiceProvider.php
  app/Support/Utils.php
  composer.json
  composer.lock
  config/installer.php
  phpunit.xml
  resources/stubs/installer/env.stub
  resources/tld/public_suffix_list.dat
  tests/SimBriefTest.php
Labels: dependencies

#1064 Restrict Simbrief to user who generated it
  app/Http/Controllers/Api/UserController.php
  app/Http/Controllers/Frontend/FlightController.php
  app/Services/BidService.php
  resources/views/layouts/default/flights/table.blade.php
  tests/SimBriefTest.php
Labels: bug

#1073 Add web cron ability #821
  app/Database/migrations/2021_03_05_044305_add_kvp_table.php
  app/Database/seeds/settings.yml
  app/Exceptions/CronInvalid.php
  app/Http/Controllers/Admin/MaintenanceController.php
  app/Http/Controllers/Admin/SettingsController.php
  app/Http/Controllers/Api/FlightController.php
  app/Http/Controllers/Api/MaintenanceController.php
  app/Models/Kvp.php
  app/Models/SimBrief.php
  app/Providers/RouteServiceProvider.php
  resources/views/admin/maintenance/cron.blade.php
  tests/ApiTest.php
  tests/UtilsTest.php
Labels: enhancement

#1076 Add unit conversion handling for block_fuel like for fuel_used
  app/Http/Resources/Pirep.php
  app/Models/Pirep.php
  tests/PIREPTest.php
Labels: enhancement

#1072 Fix Metar Decoding / Wind check for Wind Chill
  app/Support/Metar.php
  tests/MetarTest.php
Labels: bug

#1080 Update pireps/show.blade
  resources/views/layouts/default/pireps/show.blade.php
Labels: enhancement

#1079 Fix null visibility in METAR
  app/Support/Metar.php
  tests/MetarTest.php
Labels: bug

#1050 Fix for Fuel and Ground Handling Costs
  app/Services/Finance/PirepFinanceService.php
  tests/FinanceTest.php
Labels: bug

#1083 Fix Finance Memo (Ground Handling)
  app/Services/Finance/PirepFinanceService.php
Labels: bug

#1081 Optimize view paths for module views in theme folder
  app/Providers/AppServiceProvider.php
  app/Support/ThemeViewFinder.php
Labels: bug

#1087 Implemented variant B of #1078
  app/Database/factories/RoleFactory.php
  app/Database/migrations/2021_03_18_161419_add_disableactivitychecks_to_roles.php
  app/Models/Role.php
  app/Services/UserService.php
  resources/views/admin/roles/fields.blade.php
  tests/TestData.php
  tests/UserTest.php
Labels: enhancement

#1088 Fix For GH Costs
  app/Services/Finance/PirepFinanceService.php
  app/Services/Importers/AirportImporter.php
Labels: bug

#1089 Fix full aircraft retrieval for simbriefs
  app/Database/seeds/dev/simbrief.yml
  app/Http/Resources/Bid.php
  app/Http/Resources/BidFlight.php
  app/Http/Resources/BidSubfleet.php
  app/Http/Resources/Flight.php
  app/Http/Resources/SimBrief.php
  app/Models/SimBrief.php
  app/Services/BidService.php
  app/Services/FlightService.php
  tests/SimBriefTest.php
Labels: enhancement

#1091 DownloadController Improvements
  app/Http/Controllers/Frontend/DownloadController.php
Labels: enhancement

#1093 Move SimBrief aircraft selection to Controller
  app/Database/seeds/settings.yml
  app/Http/Controllers/Frontend/SimBriefController.php
  resources/views/layouts/default/flights/simbrief_aircraft.blade.php
  resources/views/layouts/default/flights/simbrief_form.blade.php
Labels: enhancement

#1094 Urgent Fix For SimBriefController
  app/Http/Controllers/Frontend/SimBriefController.php
Labels: bug

#1095 Small fix to FlightImporter
  app/Services/ImportExport/FlightImporter.php
  tests/ImporterTest.php
  tests/data/flights.csv
Labels: bug

#1099 Change LatestPireps Widget Sort Order
  app/Widgets/LatestPireps.php
Labels: enhancement

#1100 remove remove_bid_after_accept setting
  app/Database/migrations/2021_03_25_213017_remove_setting_removebidonaccept.php
  app/Database/seeds/settings.yml
  app/Listeners/BidEventHandler.php
  app/Services/BidService.php
  tests/PIREPTest.php
Labels: enhancement

#1104 fix map-info-box display
  app/Http/Controllers/Frontend/PirepController.php
  app/Http/Requests/UpdatePirepRequest.php
  public/assets/frontend/css/styles.css
  resources/views/layouts/default/pireps/show.blade.php
  resources/views/layouts/default/widgets/live_map.blade.php
Labels: bug

#1107 Followup to #1081
  app/Support/ThemeViewFinder.php
Labels: bug

#1111 Move the prefile event and add a new error exception
  app/Exceptions/PrefileError.php
  app/Http/Controllers/Api/PirepController.php
  app/Listeners/PirepEventsHandler.php
  app/Providers/EventServiceProvider.php
  app/Services/PirepService.php
Labels: enhancement

#1112 Save airport timezone
  app/Models/Airport.php
  app/Services/AirportService.php
  tests/AirportTest.php
  tests/TestCase.php
Labels: bug

#1103 fetch timezone on airport lookup
  app/Services/AirportLookup/VaCentralLookup.php
Labels: bug

#1116 Fix issue with being unable to save pirep edits
  app/Http/Requests/UpdatePirepRequest.php
Labels: bug
