Repository nabeelio/phpvms, pull requests merged in 2021-04, with the labels that each got.

#1122 Add "View Pirep" In pirep cards
  resources/views/admin/pireps/actions.blade.php
Labels: enhancement

#1123 Adds Airline Icao to Subfleet Select in Flight Create
  app/Http/Controllers/Admin/FlightController.php
Labels: enhancement

#1121 Show Airline logo / icao to subfleets table
  resources/views/admin/flights/subfleets.blade.php
Labels: enhancement

#1124 Alphanumeric Callsign For Flights
  app/Database/migrations/2021_04_05_055245_flights_add_alphanumeric_callsign.php
  app/Models/Flight.php
  resources/lang/en/flights.php
  resources/lang/es/flights.php
  resources/lang/it/flights.php
  resources/lang/pt-br/flights.php
  resources/views/admin/flights/fields.blade.php
  resources/views/layouts/default/flights/show.blade.php
  resources/views/layouts/default/flights/simbrief_form.blade.php
  resources/views/layouts/default/flights/table.blade.php
Labels: enhancement

#1127 Fix for Hourly Crons
  app/Cron/Hourly/DeletePireps.php
  app/Cron/Hourly/RemoveExpiredBids.php
  app/Cron/Hourly/RemoveExpiredLiveFlights.php
Labels: bug

#1128 Migrate all configs into the env.php file #1075
  .github/scripts/env.php
  .gitignore
  .htaccess
  Dockerfile
  app/Console/Commands/CreateConfigs.php
  app/Console/Commands/DevInstall.php
  app/Console/Commands/RewriteConfigs.php
  app/Database/migrations/2021_04_10_055245_migrate_configs.php
  app/Http/Controllers/System/InstallerController.php
  app/Services/Installer/ConfigService.php
  config/app.php
  config/logging.php
  config/services.php
  resources/docker/php/Dockerfile
  resources/stubs/installer/config.stub
  resources/stubs/installer/env.stub
  resources/views/system/installer/flash/message.blade.php
Labels: critical

#1130 Read Captcha Settings From ENV
  config/captcha.php
Labels: bug

#1131 Fix email for news not going out
  app/Notifications/EventHandler.php
  app/Notifications/Messages/NewsAdded.php
  resources/views/notifications/mail/news/news.blade.php
Labels: bug

#1136 Fix default value for Captcha setting
  config/captcha.php
Labels: bug

#1137 Use where iso whereTime
  app/Cron/Hourly/RemoveExpiredLiveFlights.php
Labels: bug

#1139 Make sure all dates are in UTC
  app/Cron/Hourly/DeletePireps.php
  app/Cron/Hourly/RemoveExpiredBids.php
  app/Cron/Hourly/RemoveExpiredLiveFlights.php
  app/Database/factories/JournalTransactionsFactory.php
  app/Models/Journal.php
  app/Repositories/JournalRepository.php
  app/Services/Installer/SeederService.php
  app/Services/PirepService.php
  tests/PIREPTest.php
Labels: bug

#1138 adds 100ll option to airport admin
  resources/views/admin/airports/fields.blade.php
  resources/views/admin/airports/table.blade.php
Labels: enhancement

#1141 Add tests for the cron jobs
  app/Cron/Hourly/DeletePireps.php
  tests/CronTest.php
Labels: core

#1143 Pirep delete confirmation
  resources/views/admin/pireps/actions.blade.php
  resources/views/layouts/default/pireps/fields.blade.php
Labels: enhancement

#1153 Add Airline ICAO to Subfleet selectBoxList
  app/Repositories/SubfleetRepository.php
Labels: enhancement

#1151 Delete the user in a GDPR compatible way
  app/Exceptions/UserNotFound.php
  app/Http/Controllers/Admin/UserController.php
  app/Http/Controllers/Api/UserController.php
  app/Models/Aircraft.php
  app/Models/Enums/UserState.php
  app/Models/User.php
  app/Notifications/EventHandler.php
  app/Services/PirepService.php
  app/Services/UserService.php
  resources/lang/en/user.php
  resources/lang/es/user.php
  resources/lang/it/user.php
  resources/lang/pt-br/user.php
  tests/AcarsTest.php
  tests/UserTest.php
Labels: enhancement
