Repository nabeelio/phpvms, pull requests merged in 2021-06, with the labels that each got.

#1218 New Language: German
  resources/lang/de/aircraft.php
  resources/lang/de/airports.php
  resources/lang/de/auth.php
  resources/lang/de/common.php
  resources/lang/de/dashboard.php
  resources/lang/de/downloads.php
  resources/lang/de/email.php
  resources/lang/de/errors.php
  resources/lang/de/expenses.php
  resources/lang/de/flights.php
  resources/lang/de/home.php
  resources/lang/de/installer.php
  resources/lang/de/pagination.php
  resources/lang/de/passwords.php
  resources/lang/de/pireps.php
  resources/lang/de/profile.php
  resources/lang/de/toc.php
  resources/lang/de/user.php
  resources/lang/de/validation.php
  resources/lang/de/widgets.php
Labels: enhancement

#1216 Fix Aircraft Dropdown Grouping
  app/Http/Controllers/Admin/PirepController.php
  app/Http/Controllers/Frontend/PirepController.php
Labels: enhancement

#1213 Block aircraft with Simbrief
  app/Cron/Hourly/ClearExpiredSimbrief.php
  app/Database/migrations/2021_05_28_165608_remove_setting_simbriefexpiredays.php
  app/Database/seeds/settings.yml
  app/Http/Controllers/Frontend/PirepController.php
  app/Http/Controllers/Frontend/SimBriefController.php
  app/Providers/CronServiceProvider.php
  app/Services/PirepService.php
  app/Services/SimBriefService.php
Labels: enhancement

#1220 Remove the IP address from being recorded
  app/Http/Controllers/Auth/LoginController.php
  resources/views/admin/users/fields.blade.php
Labels: enhancement

#1221 Add setting for recording IP address
  app/Database/seeds/settings.yml
  app/Http/Controllers/Auth/LoginController.php
  app/Http/Controllers/Auth/RegisterController.php
  app/Models/User.php
  resources/views/admin/users/fields.blade.php
Labels: enhancement

#1222 Fixed German Translation
  resources/lang/de/flights.php
Labels: enhancement

#1223 Fix data not showing up for live map
  app/Database/migrations/2021_06_04_141152_discord_private_channel_id.php
  app/Database/seeds/dev/in_progress.yml
  app/Http/Controllers/Api/PirepController.php
  app/Http/Controllers/Frontend/ProfileController.php
  app/Models/User.php
  app/Notifications/Channels/Discord/DiscordWebhook.php
  app/Notifications/Messages/AdminUserRegistered.php
  app/Notifications/Messages/NewsAdded.php
  app/Notifications/Messages/PirepPrefiled.php
  app/Notifications/Messages/PirepStatusChanged.php
  app/Notifications/Messages/PirepSubmitted.php
  app/Services/Installer/SeederService.php
  app/Support/Discord.php
  resources/views/layouts/default/pireps/show.blade.php
  resources/views/layouts/default/widgets/live_map.blade.php
Labels: bug

#1234 Fix typo
  app/Notifications/Messages/PirepStatusChanged.php
Labels: enhancement

#1241 Remove extraneous data from API response; force API to en
  app/Contracts/Resource.php
  app/Http/Middleware/ApiAuth.php
  app/Http/Middleware/JsonResponse.php
  app/Support/Resources/CustomAnonymousResourceCollection.php
  app/Support/Resources/CustomPaginatedResourceResponse.php
  tests/ApiTest.php
Labels: bug

#1228 Simbrief Edit & Download Latest OFP
  app/Http/Controllers/Frontend/SimBriefController.php
  app/Providers/RouteServiceProvider.php
  app/Services/SimBriefService.php
  config/phpvms.php
  resources/views/layouts/default/flights/simbrief_briefing.blade.php
  resources/views/layouts/default/flights/simbrief_form.blade.php
Labels: feature

#1248 Create endpoint to load bid by ID
  app/Http/Controllers/Api/UserController.php
  app/Models/Bid.php
  app/Providers/RouteServiceProvider.php
  app/Services/BidService.php
  tests/BidTest.php
Labels: enhancement
