Repository nabeelio/phpvms, pull requests merged in 2021-02, with the labels that each got.

#1018 Update style.css for better mobile experience
  public/assets/frontend/css/styles.css
Labels: enhancement

#1028 ACARS table `vs` int to double
  app/Database/migrations/2021_02_10_044305_change_acars_vs_type.php
  config/mail.php
Labels: acars, bug

#1030 Update the sessions table
  app/Database/migrations/2021_02_11_044305_update_sessions_table.php
  resources/stubs/installer/config.stub
Labels: enhancement

#1035 Fix pilot leave calculation #1022
  app/Cron/Nightly/PilotLeave.php
  app/Http/Controllers/Frontend/SimBriefController.php
  app/Models/PirepFare.php
  app/Services/FareService.php
  app/Services/UserService.php
  tests/TestData.php
  tests/UserTest.php
Labels: bug

#1037 Fix for SimBrief VATSIM Prefile errors ( Issue #1036 )
  resources/views/layouts/default/flights/simbrief_briefing.blade.php
Labels: bug

#1038 `php-dom` as one of the required extensions
  config/installer.php
Labels: enhancement

#1004 Update FlightService.php
  app/Services/FlightService.php
Labels: enhancement

#964 Update AviationWeather.php
  app/Contracts/Metar.php
  app/Services/AirportService.php
  app/Services/Metar/AviationWeather.php
  app/Widgets/Weather.php
  config/cache.php
  resources/views/layouts/default/widgets/weather.blade.php
  tests/MetarTest.php
Labels: enhancement

#1042 Fix findUsersOnleave Function
  app/Services/UserService.php
Labels: bug

#1047 Update composer dependencies
  composer.lock
Labels: dependencies, enhancement
